ALTER TABLE BILL ADD CONSTRAINT PK_BILL PRIMARY KEY (
    FEE_NUMBER
);


ALTER TABLE ANSWER ADD CONSTRAINT PK_ANSWER PRIMARY KEY (
    A_NUMBER
);


ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY (
    NTC_NUMBER
);


ALTER TABLE INQUIRY_BOARD ADD CONSTRAINT PK_INQUIRY_BOARD PRIMARY KEY (
    B_NUMBER
);


ALTER TABLE RESIDENT ADD CONSTRAINT PK_RESIDENT PRIMARY KEY (
    ID
);


ALTER TABLE PARKING_RESIDENT ADD CONSTRAINT PK_PARKING_RESIDENT PRIMARY KEY (
    ID
);


ALTER TABLE PARKING_GUEST ADD CONSTRAINT PK_PARKING_GUEST PRIMARY KEY (
    ID
);


ALTER TABLE PAYMENT ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (
    FEE_NUMBER
);


ALTER TABLE RECEIPT ADD CONSTRAINT PK_RECEIPT PRIMARY KEY(
    FEE_NUMBER
);


ALTER TABLE VBANK ADD CONSTRAINT PK_VANK PRIMARY KEY (
    PAYMENT_METHOD_ID
);


ALTER TABLE CARD ADD CONSTRAINT PK_CARD PRIMARY KEY (
    PAYMENT_METHOD_ID
);


ALTER TABLE SMS ADD CONSTRAINT PK_SMS PRIMARY KEY (
    FEE_NUMBER
);


ALTER TABLE OPERATOR ADD CONSTRAINT PK_OPERATOR PRIMARY KEY (
    OPER_ID
);


ALTER TABLE COST ADD CONSTRAINT PK_COST PRIMARY KEY (
    DETAILED_NUMBER
);


ALTER TABLE BILL ADD CONSTRAINT FK_COST_TO_BILL_1 FOREIGN KEY (
    DETAILED_NUMBER
)
REFERENCES COST (
    DETAILED_NUMBER
);


ALTER TABLE ANSWER ADD CONSTRAINT FK_INQUIRY_BOARD_ANSWER_1 FOREIGN KEY (
    B_NUMBER
)
REFERENCES INQUIRY_BOARD (
    B_NUMBER
);   
